services:
    CleverAge\ProcessBundle\EventListener\DataQueueEventListener:
        public: false
        tags:
            - { name: kernel.event_listener, event: cleverage_process.data_queue, method: pushData }
