services:
    process_bundle.manager.process:
        class: CleverAge\ProcessBundle\Manager\ProcessManager
        public: false
        arguments:
            - '@service_container'
            - '@cleverage_process.logger.process_logger'
            - '@cleverage_process.logger.task_logger'
            - '@process_bundle.registry.process_configuration'
            - '@process_bundle.context.contextual_option_resolver'
            - '@event_dispatcher'

    process_bundle.context.contextual_option_resolver:
        class: CleverAge\ProcessBundle\Context\ContextualOptionResolver
        public: false
