services:
    process_bundle.registry.process_configuration:
        class: CleverAge\ProcessBundle\Registry\ProcessConfigurationRegistry
        public: false
        arguments:
            - ~
            - ~

    process_bundle.registry.transformer:
        class: CleverAge\ProcessBundle\Registry\TransformerRegistry
        public: false
