services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $language: '@cleverage_process.expression_language'

    CleverAge\ProcessBundle\Transformer\:
        resource: '../../../Transformer/*'
        exclude: '../../../Transformer/GenericTransformer.php'
        tags:
            - { name: cleverage.transformer }
            - { name: monolog.logger, channel: cleverage_process_transformer }
