name: Google Chat notifications

# Controls when the action will run.
on:
  push:
    tags:
      - '*'

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      - name: Google Chat Notification
        env:
          WEBHOOK_URL: ${{ secrets.CLEVER_AGE_GOOGLE_CHAT_WEBHOOK_URL }}
          REPOSITORY: ${{ github.repository }}
          SERVER_URL: ${{ github.server_url }}
          TAG: ${{ github.ref_name }}
        run: |
          jq -n --arg text "<${SERVER_URL}/${REPOSITORY}|${REPOSITORY}> : <${SERVER_URL}/${REPOSITORY}/tree/${TAG}|${TAG}> has been released" '{text: $text}' \
            | curl --fail-with-body -sS -X POST -H 'Content-Type: application/json; charset=UTF-8' --data @- "$WEBHOOK_URL"
